from typing import Any, Sequence

class RecursiveCharacterTextSplitter:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def split_text(self, text: str) -> list[str]: ...
    def split_documents(self, docs: Sequence[Any]) -> list[Any]: ...
