from __future__ import annotations
from typing import Any

class AppTest:
    @classmethod
    def from_file(cls, *args: Any, **kwargs: Any) -> "AppTest": ...
    def run(self) -> None: ...
    @property
    def dataframe(self) -> list[Any]: ...
    @property
    def data_editor(self) -> list[Any]: ...
    @property
    def button(self) -> list[Any]: ...
    @property
    def markdown(self) -> list[Any]: ...
    @property
    def selectbox(self) -> list[Any]: ...
    @property
    def success(self) -> list[Any]: ...
    @property
    def info(self) -> list[Any]: ...
    @property
    def title(self) -> list[Any]: ...
    def switch_page(self, *args: Any, **kwargs: Any) -> "AppTest": ...
    @property
    def _tree(self) -> Any: ...
