from typing import Any

class Chart:
    def __init__(self, data: Any = None) -> None: ...
    def mark_bar(self, *args: Any, **kwargs: Any) -> "Chart": ...
    def mark_rule(self, *args: Any, **kwargs: Any) -> "Chart": ...
    def encode(self, *args: Any, **kwargs: Any) -> "Chart": ...
    def properties(self, *args: Any, **kwargs: Any) -> "Chart": ...
    def __add__(self, other: Any) -> "Chart": ...

class Bin:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class X:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class Y:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

