from typing import Any
from langchain_core.documents import Document

class TextLoader:
    def __init__(self, file_path: str, **kwargs: Any) -> None: ...
    def load(self) -> list[Document]: ...

class PyPDFLoader:
    def __init__(self, file_path: str, **kwargs: Any) -> None: ...
    def load(self) -> list[Document]: ...

class Docx2txtLoader:
    def __init__(self, file_path: str, **kwargs: Any) -> None: ...
    def load(self) -> list[Document]: ...
