from typing import Any

class HDBSCAN:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def fit_predict(self, *args: Any, **kwargs: Any) -> Any: ...
    def fit(self, *args: Any, **kwargs: Any) -> Any: ...
    probabilities_: Any

