from typing import Any, Callable

class Celery:
    conf: Any
    control: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def task(self, *args: Any, **kwargs: Any) -> Callable[[Callable[..., Any]], Any]: ...
    def send_task(self, *args: Any, **kwargs: Any) -> Any: ...
    def signature(self, *args: Any, **kwargs: Any) -> Any: ...
    def AsyncResult(self, *args: Any, **kwargs: Any) -> Any: ...
