from __future__ import annotations
from typing import Any, Iterable, Mapping, Sequence

class Series:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __getitem__(self, key: Any) -> Any: ...
    def to_list(self) -> list[Any]: ...
    def unique(self) -> list[Any]: ...

class DataFrame:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __len__(self) -> int: ...
    def copy(self) -> DataFrame: ...
    def head(self, *args: Any, **kwargs: Any) -> DataFrame: ...
    def drop(self, *args: Any, **kwargs: Any) -> DataFrame: ...
    def dropna(self, *args: Any, **kwargs: Any) -> DataFrame: ...
    def fillna(self, *args: Any, **kwargs: Any) -> DataFrame: ...
    def map(self, *args: Any, **kwargs: Any) -> Series: ...
    def sort_values(self, *args: Any, **kwargs: Any) -> DataFrame: ...
    def to_dict(self, *args: Any, **kwargs: Any) -> list[dict[str, Any]]: ...
    def to_csv(self, *args: Any, **kwargs: Any) -> str: ...
    def reset_index(self, *args: Any, **kwargs: Any) -> DataFrame: ...
    def astype(self, *args: Any, **kwargs: Any) -> DataFrame: ...
    def groupby(self, *args: Any, **kwargs: Any) -> Any: ...

class NAType: ...

NA: NAType

