from typing import Any
from . import helpers, exceptions

class _Indices:
    def exists(self, *args: Any, **kwargs: Any) -> bool: ...
    def create(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_mapping(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    def put_mapping(self, *args: Any, **kwargs: Any) -> Any: ...
    def refresh(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete(self, *args: Any, **kwargs: Any) -> Any: ...

class OpenSearch:
    indices: _Indices
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def search(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    def mget(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    def index(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    def count(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    def delete(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    def update(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    def get(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    def delete_by_query(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    def update_by_query(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    def scroll(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    def clear_scroll(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
