from __future__ import annotations
from typing import Any, Callable, Iterable, Mapping, MutableMapping, Sequence, Protocol

class _SessionState(MutableMapping[str, Any]):
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def get(self, key: str, default: Any = ...) -> Any: ...
    def pop(self, key: str, default: Any = ...) -> Any: ...
    def setdefault(self, key: str, default: Any = ...) -> Any: ...
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...

session_state: _SessionState

class _Spinner:
    def __enter__(self) -> None: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: Any) -> None: ...

class _Expander:
    def __enter__(self) -> None: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: Any) -> None: ...

class column_config:
    class NumberColumn:
        def __init__(self, *args, **kwargs) -> None: ...
    class TextColumn:
        def __init__(self, *args, **kwargs) -> None: ...
    class CheckboxColumn:
        def __init__(self, *args, **kwargs) -> None: ...

class Page:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

sidebar: Any


def set_page_config(*args: Any, **kwargs: Any) -> None: ...

def title(*args: Any, **kwargs: Any) -> None: ...

def subheader(*args: Any, **kwargs: Any) -> None: ...

def caption(*args: Any, **kwargs: Any) -> None: ...

def write(*args: Any, **kwargs: Any) -> None: ...

def markdown(*args: Any, **kwargs: Any) -> None: ...

def json(*args: Any, **kwargs: Any) -> None: ...

def info(*args: Any, **kwargs: Any) -> None: ...

def warning(*args: Any, **kwargs: Any) -> None: ...

def error(*args: Any, **kwargs: Any) -> None: ...

def success(*args: Any, **kwargs: Any) -> None: ...

def table(*args: Any, **kwargs: Any) -> None: ...

def dataframe(*args: Any, **kwargs: Any) -> None: ...

def data_editor(*args: Any, **kwargs: Any) -> Any: ...

def empty() -> Any: ...

def columns(spec: Any, **kwargs: Any) -> list[Any]: ...

def tabs(tabs: Sequence[str]) -> list[Any]: ...

def expander(*args: Any, **kwargs: Any) -> _Expander: ...

def spinner(*args: Any, **kwargs: Any) -> _Spinner: ...

def button(*args: Any, **kwargs: Any) -> bool: ...

def checkbox(*args: Any, **kwargs: Any) -> bool: ...

def selectbox(*args: Any, **kwargs: Any) -> Any: ...

def radio(*args: Any, **kwargs: Any) -> Any: ...

def multiselect(*args: Any, **kwargs: Any) -> list[Any]: ...

def slider(*args: Any, **kwargs: Any) -> Any: ...

def text_input(*args: Any, **kwargs: Any) -> str: ...
def text_area(*args: Any, **kwargs: Any) -> str: ...

def number_input(*args: Any, **kwargs: Any) -> Any: ...

def download_button(*args: Any, **kwargs: Any) -> None: ...

class _CachedFunc(Protocol):
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def clear(self) -> None: ...

class _CacheDecorator(Protocol):
    def __call__(self, *args: Any, **kwargs: Any) -> Callable[[Callable[..., Any]], _CachedFunc]: ...
    def clear(self) -> None: ...

cache_data: _CacheDecorator
cache_resource: _CacheDecorator

def divider() -> None: ...
def progress(*args: Any, **kwargs: Any) -> Any: ...
def toggle(*args: Any, **kwargs: Any) -> bool: ...
def text(*args: Any, **kwargs: Any) -> None: ...
def container(*args: Any, **kwargs: Any) -> Any: ...
def form(*args: Any, **kwargs: Any) -> Any: ...
def form_submit_button(*args: Any, **kwargs: Any) -> bool: ...
def chat_message(*args: Any, **kwargs: Any) -> Any: ...
def chat_input(*args: Any, **kwargs: Any) -> Any: ...
def toast(*args: Any, **kwargs: Any) -> None: ...
def rerun() -> None: ...
def stop() -> None: ...
def page_link(*args: Any, **kwargs: Any) -> None: ...
def date_input(*args: Any, **kwargs: Any) -> Any: ...
def code(*args: Any, **kwargs: Any) -> None: ...
def metric(*args: Any, **kwargs: Any) -> None: ...
def altair_chart(*args: Any, **kwargs: Any) -> None: ...
def navigation(*args: Any, **kwargs: Any) -> Any: ...
def switch_page(*args: Any, **kwargs: Any) -> None: ...
