# .github/workflows/tests.yml
name: Unit tests

on: 
  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: |
            requirements/shared.txt
            requirements/dev.txt
            requirements/app.txt
            requirements/worker.txt

      - name: Run tests
        shell: bash
        run: bash scripts/test.sh
